services:
  learnease-api:
    image: learneaseapi:dev
    container_name: "LearnEase-Api_1"
    build:
      args:
        LAUNCHING_FROM_VS: true
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "LearnEase-Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/.nuget/fallbackpackages
    volumes:
      - E:\Team Project\NWD\API\learnEase-api\LearnEase-Api:/app:rw
      - E:\Team Project\NWD\API\learnEase-api:/src:rw
      - C:\Users\minho\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\minho\.nuget\packages:/.nuget/packages:ro
      - D:\visual code\shared\NuGetPackages:/.nuget/fallbackpackages:ro
      - C:\Users\minho\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\minho\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\minho\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\minho\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - D:\visual code\comunity\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - D:\visual code\comunity\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages --additionalProbingPath /.nuget/fallbackpackages  \"/app/bin/Debug/net8.0/LearnEase-Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true