version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis-service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    configs:
      - source: redis_config
        target: /usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: always

volumes:
  redis_data:

configs:
  redis_config:
    file: ../1/redis.conf
